- src/SearchableTrait.php
I tried to use the search with joins ex:
  protected $ searchable = [
         'columns' => [
             'cities.name' => 10,
             'states.name' => 10
         ]
         'joins' => [
             'states' => ['states.id', 'cities.state_id'],
         ]
     ];
but there errors in joins with group by, and decided that way.
> Bug fix in group by with joins

- src/SearchableTrait.php
fix class Str not found introduced from previous commit.
> fix Class 'Nicolaslopezj\Searchable\Str' not found

- README.md
- src/SearchableTrait.php
By putting the search query in a sub FROM clause it fixes the issues with Laravel 5 trying to use count() and thus also the pagination. So it fixes #21 and #23.
> Fix #21 and #23

- src/SearchableTrait.php
The method scopeSearch returns the old $q query cloned at the first line. 
I've change it to $query, because the $q throw a QueryException Column Not Found.
> Fix scopeSearch, it returned the cloned query $q instead of new $query

- src/SearchableTrait.php
If i'm searching for **Saving Private**, i would like that **Saving Private Ryan** have a better result that **Saving The animals, private detective** (that movie doesn't exists). 
I implemented the code in a NON breaking change way, so the flag is false by default. You may want to set this to true often, but i'll let you decide what's the best
> Add the possibility to search for the whole text

- README.md
- src/SearchableTrait.php
This pull request implements a better EntireWord Search that gives more relevance to results that starts with the entire search...
Some cases like this search: `Lucas do rio`
May not show the result `Lucas do Rio Verde` as first result in this table:
```
Lucas do Rio Verde
Bahia dos santos do Brasil (Rio grande do sul)
Do do do do (Rio grande do sul)
```
In my PR:
* I give a relevance multiplier of `30` to a search `LIKE 'lucas do%'`. This fix the problem above.
* I added a `trim()` to search, to avoid blank spaces to causing performance issues.
* Moved $like_comparator variable from `filterQueryWithRelevance()` to `getSearchQuery()` method
> Improved EntireWord Search

- src/SearchableTrait.php
In case you're working with locales where decimal point are not used, FE, using commas, relevance_count should be converted for the query not to fail.
This happens when the division is not whole and it has decimals.
> fix when not using decimal points for numbers

- src/SearchableTrait.php
When using different connections for different models, using the default connection to determine the database driver may cause issues, especially when different models use different database drivers. This pull request fixes this issue by always using the current model's connection.
> Use the model's connection to determine database driver.

- src/SearchableTrait.php
I have a case where I required to add a "where" into the inner select, e.g.
```sql
select 
* 
from 
(select 
`products`.*, 
(case when LOWER(`product_localizations`.`name`) LIKE 'word' then 750 else 0 end) + ...
from 
`products` 
left join 
`product_localizations` on `products`.`id` = `product_localizations`.`product_id` 
where 
`product_localizations`.`language_id` in ('41')
group by 
...
having 
relevance > 22.50 
order by 
`relevance` desc
) 
as 
`products`
``` 
I need this since I only want to search trough the localizations of the users's language. So I propose this change where a second method (```searchRestricted```) allows to modify the search query before merging:
```php
$this->result = Product::searchRestricted("word", function($query) {
return …
```
> Add a "where" clause to the inner select

- src/SearchableTrait.php
The threshold was defaulting to `relevance_count / 4` if the passed threshold value was not truthy, causing the method for disabling the threshold - passing zero, as noted in the documentation - to fail.
This patch changes the behaviour such the threshold is only calculated if the given value is null, which is what the value defaults to if it is not passed.  Any other value that is passed to the function will always be respected.
> Fix being unable to disable threshold

- src/SearchableTrait.php
This is so that there are no collisions or issues if someone renames the alias for DB or Config within their Laravel app. I actually had to rename both of these aliases (unfortunately I have some legacy code using PEAR's DB class :cry:) in my Laravel app.
@nicolaslopezj - do you see any issues doing this? Thought this might make this package a bit more robust. :sunglasses:
> Remove Laravel aliases and call facades directly

- src/SearchableTrait.php
This checks to see if the values in `$this->searchable['joins']` have a 3rd & 4th value and, if so, implements those as a where clause on the leftJoin. This allows you to join polymorphic relations with something like this:
```php
protected $searchable = [
'columns' => [
'posts.title' => 15,
'posts.description' => 10,
'tags.name' => 7
],
'joins' => [
'taggables' => ['posts.id','taggables.taggable_id','taggables.taggable_type','App\Post'],
'tags' => ['taggables.tag_id','tags.id'],
],
];
```
Addresses issue #64 in particular, but you could also use this to do any kind of additional advanced join filtering.
> Add polymorphic capability to joins.

- src/SearchableTrait.php
Improved https://github.com/nicolaslopezj/searchable/pull/70 (so it will not break as in https://github.com/nicolaslopezj/searchable/issues/71). Also execute `DB::raw()` on the model's connection (see http://laravel.com/docs/5.1/database#accessing-connections).
Jarno
> Added support for multiple connections.

- src/SearchableTrait.php
This pull request fixes #75 and possibly more issues. The problem is that a GROUP BY clause is used (to remove duplicates?), but there is no aggregate over the relevance score.
> Added average aggregate function to relevance scores (fixes #75)

- src/SearchableTrait.php
Using joins to allow a broader search can lead to duplicate rows if the joined tables are not physically shown in the results list. With this pull request the developer can choose whether or not to keep duplicates by manually setting the group by clause.
class Account extends Model
{
use SearchableTrait;
/**
* @var array
*/
protected $searchable = [
'columns' => [
// ...
],
'joins' => [
// ...
],
'groupBy' => 'accounts.id' // defaults to false
];
The default value of the `groupBy` option is false, in which case the old group by clause is used. Otherwise, the provided value will be used to group by. Furthermore, this pull requests fixes a bug where `$ids` is undefined in the case of a SQLSRV driver.
> Added the option to control whether or not to keep duplicates in the results

- src/SearchableTrait.php
As mentioned in #87 
>One comment however - isn't it better to use the MAX function here instead of average?
>
>For example, imagine we had a Post model with a relationship to comments, and we have 10 comments to join. If our search term only matches one of those comments, we surely want that post's relevance to be the weight that we give a comment match (e.g. a weight of 10). Using AVG, with 10 comments and a weight of 10, we would get a post relevance of 1 in this case - which isn't the weight of 10 we defined in the model. If we used MAX however, then the returned relevance of 10 will cascade up to the Post.
>
>Am I thinking through that correctly? I'll submit a PR changing the function to max, and we can discuss it there.
> Use MAX function for relevance aggregation

- src/SearchableTrait.php
If you use custom table prefix in laravel orm database configuration you should set it in query "select (conds) as `{prefix}table`" to avoid conflicts with other traits like softDeletes (default eloquent trait).
Issue was descripted in https://github.com/nicolaslopezj/searchable/issues/101
> Phpdoc, fix using eloquent table prefix

- src/SearchableTrait.php
The bindings order were wrong. The following code includes published scope which is `$query->where('published_at', '<=', Carbon::now());` .. 
`$articles = Article::with('category')->published()->search($request->get('q'))->paginate(10);`
params are:
0	2016-12-10 10:56:21
1	2016-12-10 10:56:21
2	test
3	test%
4	%test%
5	test
6	test%
7	%test%
which is wrong. 
Correct Params should have been with this order : 
```
0	test
1	test%
2	%test%
3	test
4	test%
5	%test%
6	2016-12-10 10:56:21
7	2016-12-10 10:56:21
```
My sql was like : (date and query params were at wrong places.)
select count(*) as aggregate from (select articles.*, max((case when LOWER(articles.title) **LIKE '2016-12-10 10:56:21'**' then 300 else 0 end) ..... bla bla bla.... having relevance > 7.50 order by relevance desc) as …
> fix for bindings order when using where clause

- .gitignore
- src/.gitignore
- src/SearchableTrait.php
Even with Tamrael's modifications I still had the issue that using search with global scopes did not work. I noticed that even assigning new bindings to the original request in `mergeQueries` an old binding was still there.
For example, if my original bindigns where
`
[ 0 => 'binding 1', 1 => 'binding 2' ]
`
Then new bindings would be
`
[ 0 => 'binding 1', 1 => 'Search pattern', 2 => 'Search pattern%', 3 => '%Search pattern%', 4 => 'binding 1',  ]
`
The first binding should not be there. The solution was to add new bindings out of the scope adding `withoutGlobalScopes`
> Fix bug #93 completing Tamrael's modification

- src/SearchableTrait.php
The code for non-mysql drivers produced a bug, as the `$selects` contained placeholders but no parameters were bound to these placeholders. Simply adding the `$this->search_bindings` to the statement fixed the bug
> fixed pgsql bug

- src/SearchableTrait.php
Laravel helpers are replaced on version >= 5.7
> Replace the helper with the static method

- composer.json
As there is no breaking change for illuminate/database from 5 to 6, allowing Laravel 6.0 is OK.
This is an alternative of #198 with wider and normalized versions range.
> Allow Laravel 6.0
